name: Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Calling Test Workflow and Pass secrets
      uses: ./.github/workflows/tests.yml  # use the callable tests job to run tests
      with:
        api_key: ${{ secrets.SERPLY_API_KEY }}
      if: success() || failure()

  deploy:
    if: steps.tests.outputs.exit_code == 0
    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}